apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: kaniko-build
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/nykraj/-knative-deploy
      revision: master
  template:
    name: kaniko
    arguments:
    - name: IMAGE
      value: de.icr.io/icici-demo/knative-node-kaniko