apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    build.knative.dev/docker-0: de.icr.io  # Described below
type: kubernetes.io/basic-auth
stringData:
  username: token
  password: 91TjKQgcpB51a9PK_DYAXsJ4xJcZxYVEXlZZVgkSnLEr